# Generated by Django 4.0.3 on 2022-06-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_train_route_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train_route',
            old_name='start',
            new_name='From',
        ),
        migrations.RenameField(
            model_name='train_route',
            old_name='end',
            new_name='To',
        ),
    ]
