# Generated by Django 4.0.3 on 2022-06-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_start_train_route_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_route',
            name='code',
            field=models.CharField(max_length=7),
        ),
    ]
