# Generated by Django 4.0.3 on 2022-06-25 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_alter_train_route_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_route',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='train_route',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useraddress', models.CharField(max_length=100)),
                ('userphonenumber', models.IntegerField()),
                ('pnr_number', models.CharField(blank=True, max_length=10, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.train_route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
